apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-uvin
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rick-tenant/my-app-1/devfile-sample-python-basic-uvin@sha256:5e94ada1ceede63ae4c9a24d5ec764315b2acb19afb38725eb36501344adbf58
        name: my-python
        resources: {}
status: {}
